title: Your Site Title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write your site description here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://username.github.io" # the base hostname & protocol for your site
timezone: America/New York
theme: minima
